### ISSUE TITLE
Assertion `t >= 0 && t < n_classes` failed

### ISSUE THREAD

**Issue by kjafari** [hszhao/semseg#29]
Thanks for sharing your codes! I was not able to run the training code for Cityscapes dataset. Below you can see my configuration file and the error messages. This seems to be related to the labels being out of range. I looked at your loader (SemData). It reads the label files (in my case color label files from Cityscapes dataset) but does not convert them to the range [0, n_classes-1]. Could you have a look at it? Thanks a lot!

DATA:
  data_root: /content/CityScapes_modified
  train_list: dataset/cityscapes/fine_train.txt
  val_list: dataset/cityscapes/fine_val.txt
  classes: 19

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 713
  train_w: 713
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 4  # data loader workers
  batch_size: 2  # batch size for training
  batch_size_val: 2  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/cityscapes/pspnet50/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: dataset/cityscapes/fine_val.txt
  split: val  # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 713
  test_w: 713
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: exp/dataset/cityscapes/pspnet50/model/train_epoch_200.pth  # evaluation model path
  save_folder: exp/dataset/cityscapes/pspnet50/result/epoch_200/val/ss  # results save folder
  colors_path: dataset/cityscapes/cityscapes_colors.txt  # path of dataset colors
  names_path: dataset/cityscapes/cityscapes_names.txt  # path of dataset category names

#######################################################################
Error messages:
.
.
.
Totally 2975 samples in train set.
Starting Checking image&label pair train list...
Checking image&label pair train list done!
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [160,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [161,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [162,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [163,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [164,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [165,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [166,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [167,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [168,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [256,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [257,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [258,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [259,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [260,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [261,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [262,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [263,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [264,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [3,0,0], thread: [265,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu line=127 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/semseg-master/tool/train.py", line 426, in <module>
    main()
  File "/content/semseg-master/tool/train.py", line 107, in main
    main_worker(args.train_gpu, args.ngpus_per_node, args)
  File "/content/semseg-master/tool/train.py", line 236, in main_worker
    loss_train, mIoU_train, mAcc_train, allAcc_train = train(train_loader, model, optimizer, epoch)
  File "/content/semseg-master/tool/train.py", line 281, in train
    output, main_loss, aux_loss = model(input, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/semseg-master/model/pspnet.py", line 102, in forward
    main_loss = self.criterion(x, y)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 916, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2009, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1840, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THCUNN/generic/SpatialClassNLLCriterion.cu:127

**Comment by deepakksingh** [comment]
I'm also facing the same issue.

**Comment by xjadolphx** [comment]
I'm also facing the same issue.

**Comment by deepakksingh** [comment]
did anyone find solution this issue?

**Comment by kjafari** [comment]
I corrected SemData class by adding parts of the scrips from https://github.com/meetshah1995/pytorch-semseg. This is how I corrected the SemData class in dataset.py:

class SemData(Dataset):
    def __init__(self, split='train', data_root=None, data_list=None, transform=None):
        self.split = split
        self.data_list = make_dataset(split, data_root, data_list)
        self.transform = transform

        self.void_classes = [0, 1, 2, 3, 4, 5, 6, 9, 10, 14, 15, 16, 18, 29, 30, -1]
        self.valid_classes = [
            7,
            8,
            11,
            12,
            13,
            17,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            31,
            32,
            33,
        ]
        self.class_names = [
            "unlabelled",
            "road",
            "sidewalk",
            "building",
            "wall",
            "fence",
            "pole",
            "traffic_light",
            "traffic_sign",
            "vegetation",
            "terrain",
            "sky",
            "person",
            "rider",
            "car",
            "truck",
            "bus",
            "train",
            "motorcycle",
            "bicycle",
        ]
        self.ignore_index = 255
        self.class_map = dict(zip(self.valid_classes, range(len(self.valid_classes))))


    def __len__(self):
        return len(self.data_list)

    def encode_segmap(self, mask):
        # Put all void classes to zero
        for _voidc in self.void_classes:
            mask[mask == _voidc] = self.ignore_index
        for _validc in self.valid_classes:
            mask[mask == _validc] = self.class_map[_validc]
        return mask

    def __getitem__(self, index):
        image_path, label_path = self.data_list[index]
        image = cv2.imread(image_path, cv2.IMREAD_COLOR)  # BGR 3 channel ndarray wiht shape H * W * 3
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # convert cv2 read image from BGR order to RGB order
        image = np.float32(image)
        label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)  # GRAY 1 channel ndarray with shape H * W

        label = self.encode_segmap(np.array(label, dtype=np.uint8))

        if image.shape[0] != label.shape[0] or image.shape[1] != label.shape[1]:
            raise (RuntimeError("Image & label shape mismatch: " + image_path + " " + label_path + "\n"))
        if self.transform is not None:
            image, label = self.transform(image, label)
        return image, label

**Comment by swjtulinxi** [comment]
hello,i want to know the train_h and train_w are random_crop or resize?,please explain it when you see it

**Comment by kjafari** [comment]
train_h and train_w are for final random crop after other augmentations like scaling, rotating, etc.

**Comment by swjtulinxi** [comment]
you mean we do not use the full size for training ,we use the random cropsize for training?------------------ 原始邮件 ------------------
发件人: "Kourosh Jafari-Khouzani"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 凌晨5:56
收件人: "hszhao/semseg"<semseg@noreply.github.com>;
抄送: "swjtulinxi"<1335452106@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [hszhao/semseg] Assertion `t >= 0 && t < n_classes` failed (#29)



train_h and train_w are for final random crop after other augmentations like scaling, rotating, etc.
 
&mdash;

**Comment by kjafari** [comment]
Correct, we use random cropping for training (it's random since crop_type='rand' in the script). That means the full size image is not used.

**Comment by swjtulinxi** [comment]
But  sometimes,the random crop will not cover the full image,it influence the results ------------------ 原始邮件 ------------------
发件人: "Kourosh Jafari-Khouzani"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 上午9:40
收件人: "hszhao/semseg"<semseg@noreply.github.com>;
抄送: "swjtulinxi"<1335452106@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [hszhao/semseg] Assertion `t >= 0 && t < n_classes` failed (#29)



Correct, we use random cropping for training (it's random since crop_type='rand' in the script). That means the full size image is not used.
 
&mdash;

**Comment by swjtulinxi** [comment]
hi,cao you tell me the meaning and effect of zoom_factor and world_size?,i don't know why we need it

**Comment by YLONl** [comment]
I got the problem when I first sh tool/train.sh ade20k pspnet50 .
WHO got the same error?

Traceback (most recent call last):
  File "tool/test.py", line 255, in <module>
    main()
  File "tool/test.py", line 117, in main
    raise RuntimeError("=> no checkpoint found at '{}'".format(args.model_path))
RuntimeError: => no checkpoint found at 'exp/ade20k/pspnet50/model/train_epoch_100.pth'

DATA:
  data_root: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k
  train_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/training.txt
  val_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/validation.txt
  classes: 2

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [5, 6]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/ade20k/pspnet50/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/validation.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [5]
  model_path: exp/ade20k/pspnet50/model/train_epoch_100.pth  # evaluation model path
  save_folder: exp/ade20k/pspnet50/result/epoch_100/val/ss  # results save folder
  colors_path: dataset/ade20k/ade20k_colors.txt  # path of dataset colors
  names_path: dataset/ade20k/ade20k_names.txt  # path of dataset category names

**Comment by swjtulinxi** [comment]
hi ，your program is set to save the last two .pth,however ,how can i know whicn .pth is the best one during training ???

**Comment by cobbwho** [comment]
I think I may have found what the problem is. As we all know, the **class index** is represented by the **brightness value** in the **label file** (or img). Secondly, the error log also shows that it is **because of the class label index <=0 or > n_classes**. So there should be an error in the label file, not a code problem.

For example, taking **cityscapes** as an example, the value of classes is **19** in the yaml file. Therefore, the range of the pixel value (brightness or label value) in the label image should be  **[0-18]** and **255** for ignored_label.
For example, taking **ade20k** as an example, the value of classes is **150** in the yaml file. Therefore, the range of **the pixel value (brightness or label value)** in the label image should be  **[0-149]** and **255** for ignored_label.

So, There may be a problem when completing the label mapping work (**cityscapes : json2labeltrainid.png, ade20k : seg.png2labeltrainid.png**). For example, the class index are numbered starting from 1, causing the maximum class index bigger than n_classes. Recently I found this problem when dealing with ade20k's 3148 class mapping to 150 class mapping work (convert ADE_train_*_seg.png to pspnet's gray format).

**Comment by xjadolphx** [comment]
！！！Thxs！

cobbwho <notifications@github.com> 于2020年10月27日周二 下午4:10写道：

**Comment by hyclover** [comment]
I also encountered into this problem recently. Maybe it's because of the way reading label image in the code.
`label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)  # GRAY 1 channel ndarray with shape H * W`
When I used colored label image for training, it threw an error like `Assertion `t >= 0 && t < n_classes` failed`. I replaced the code with:`label = np.array(Image.open(label_path))` and finally, it worked.
Then I compared these two methods. I loaded the same label image with color in both ways and observed their values as followed:
cv2.imread:
![image](https://user-images.githubusercontent.com/44492334/104291395-6fd74900-54f6-11eb-8f81-1d8ab3422a0c.png)
Image.open:
![image](https://user-images.githubusercontent.com/44492334/104291479-8a112700-54f6-11eb-947d-ed0061ac4494.png)
So, I am quite curious about what the reason for this. I look forward to somebody's answer.

**Comment by CuiShaohua** [comment]
I have checked my dataset in  right label method, such as ade20k. but GPU memory rate is only 10%, who also encounter this problem?
 
![image](https://user-images.githubusercontent.com/44472417/104315431-e6d00a00-5515-11eb-81ac-6c679ae96efd.png)
