### ISSUE TITLE
PSANet is stuck in modeling

### ISSUE THREAD

**Issue by eugenelawrence** [hszhao/semseg#3]
I have tried to train PSPNet50 and PSANet50.
PSPNet has been successfully trained, but PSANet is stuck in building up model.
Has anyone encountered similar problem?

**Comment by hszhao** [comment]
Maybe you can post some log information during the building process. And also the versions of different packages.

**Comment by eugenelawrence** [comment]
I try to debug the process, and I find that it is stuck in `from model.psanet import PSANet`. Then I cut down the process, and it shows:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/X/semseg/model/psanet.py", line 5, in <module>
    import lib.psa.functional as PF
  File "/home/X/semseg/lib/psa/functional.py", line 3, in <module>
    from . import functions
  File "/home/X/semseg/lib/psa/functions/__init__.py", line 1, in <module>
    from .psamask import *
  File "/home/X/semseg/lib/psa/functions/psamask.py", line 3, in <module>
    from .. import src
  File "/home/X/semseg/lib/psa/src/__init__.py", line 18, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/home/X/local/anaconda/envs/X/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/X/local/anaconda/envs/X/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 818, in _jit_compile
    baton.wait()
  File "/home/X/local/anaconda/envs/X/lib/python3.6/site-packages/torch/utils/file_baton.py", line 49, in wait
    time.sleep(self.wait_seconds)

It seems that the process is stuck in a lock. Can you provide some advice for solving the problem or outputting more information? @hszhao 

**Environments:**
Centos7
CUDA10
Python3.6
Pytorch1.0

**Comment by eugenelawrence** [comment]
I have worked it out, so I close the issue.

**Comment by Hydrogenion** [comment]
> I have worked it out, so I close the issue.

How to solve it?

**Comment by eugenelawrence** [comment]
> > I have worked it out, so I close the issue.
> 
> How to solve it?

I solve it by removing the `build_directory` in [lib/psa/src/\_\_init\_\_.py](https://github.com/hszhao/semseg/blob/master/lib/psa/src/__init__.py)
