### ISSUE TITLE
RuntimeError: => no checkpoint found at 'exp/ade20k/pspnet50/model/train_epoch_100.pth'

### ISSUE THREAD

**Issue by YLONl** [hszhao/semseg#35]
I got the problem when I first sh tool/train.sh ade20k pspnet50 .

Traceback (most recent call last):
  File "tool/test.py", line 255, in <module>
    main()
  File "tool/test.py", line 117, in main
    raise RuntimeError("=> no checkpoint found at '{}'".format(args.model_path))
RuntimeError: => no checkpoint found at 'exp/ade20k/pspnet50/model/train_epoch_100.pth'

DATA:
  data_root: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k
  train_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/training.txt
  val_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/validation.txt
  classes: 2

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [5, 6]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/ade20k/pspnet50/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /home/zhangxl003/sheyulong/semseg-master/dataset/ade20k/list/validation.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [5]
  model_path: exp/ade20k/pspnet50/model/train_epoch_100.pth  # evaluation model path
  save_folder: exp/ade20k/pspnet50/result/epoch_100/val/ss  # results save folder
  colors_path: dataset/ade20k/ade20k_colors.txt  # path of dataset colors
  names_path: dataset/ade20k/ade20k_names.txt  # path of dataset category names

**Comment by xjadolphx** [comment]
https://github.com/hszhao/semseg#usage

![image](https://user-images.githubusercontent.com/24194685/72514098-02fc8500-3889-11ea-85a4-e053c190a04d.png)

**Comment by wlj567** [comment]
> 
Traceback (most recent call last):
  File "test.py", line 216, in <module>
    test(args)
  File "test.py", line 154, in test
    raise RuntimeError ("=> no checkpoint found")
RuntimeError: => no checkpoint found
> 
Hello, how is it that it only reports this error?
