### ISSUE TITLE
When I want to use the code of PSANet， I meet this error subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. . need help. thanks.

### ISSUE THREAD

**Issue by zhengxinvip** [hszhao/semseg#36]
Traceback (most recent call last):
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 949, in _build_extension_module
    check=True)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 36, in <module>
    from models.psanet.psanet import PSANet
  File "/mnt/sda7/seg-master/seg-master/sun/models/psanet/psanet.py", line 5, in <module>
    import models.psanet.lib.psa.functional as PF
  File "/mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/functional.py", line 3, in <module>
    from . import functions
  File "/mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/functions/__init__.py", line 1, in <module>
    from .psamask import *
  File "/mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/functions/psamask.py", line 3, in <module>
    from .. import src
  File "/mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/__init__.py", line 18, in <module>
    ], build_directory=gpu_path, verbose=False)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 866, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 962, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'psamask_gpu': b'[1/3] /usr/local/cuda-10.0/bin/bin/nvcc -DTORCH_EXTENSION_NAME=psamask_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/TH -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/bin/include -isystem /home/wuwenfu/.conda/envs/pytorch/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options \'-fPIC\' -std=c++11 -c /mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/gpu/psamask_cuda.cu -o psamask_cuda.cuda.o\nFAILED: psamask_cuda.cuda.o \n/usr/local/cuda-10.0/bin/bin/nvcc -DTORCH_EXTENSION_NAME=psamask_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/TH -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/bin/include -isystem /home/wuwenfu/.conda/envs/pytorch/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options \'-fPIC\' -std=c++11 -c /mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/gpu/psamask_cuda.cu -o psamask_cuda.cuda.o\n/bin/sh: 1: /usr/local/cuda-10.0/bin/bin/nvcc: not found\n[2/3] c++ -MMD -MF operator.o.d -DTORCH_EXTENSION_NAME=psamask_gpu -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/TH -isystem /home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-10.0/bin/include -isystem /home/wuwenfu/.conda/envs/pytorch/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/gpu/operator.cpp -o operator.o\nIn file included from /mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/gpu/operator.h:1:0,\n                 from /mnt/sda7/seg-master/seg-master/sun/models/psanet/lib/psa/src/gpu/operator.cpp:1:\n/home/wuwenfu/.conda/envs/pytorch/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]\n #warning \\\n  ^\nninja: build stopped: subcommand failed.\n'

I need help . thanks.

**Comment by tjzjp** [comment]
I met the same problem, have you solved it? THANKS!
